version: "3.9"

services:

  documentdb-service:
    image: mongo:4.4-bionic
    container_name: documentdb-service
    hostname: documentdb-service
    volumes:
      - "/data/db:/opt/sharenow-coding-challenge-data/mongodb"
    ports:
    - "27017:27017"

  naming-service:
    image: teenthofabud/sharenow-coding-challenge-naming-service:1.0.0-SNAPSHOT
    container_name: naming-service
    hostname: naming-service
    ports:
    - "8761:8761"

  configuration-service:
    image: teenthofabud/sharenow-coding-challenge-configuration-service:1.0.0-SNAPSHOT
    container_name: configuration-service
    hostname: configuration-service
    ports:
    - "8888:8888"

  tracing-service:
    image: openzipkin/zipkin
    container_name: tracing-service
    hostname: tracing-service
    ports:
      - "9411:9411"

  polygon-service:
    image: teenthofabud/sharenow-coding-challenge-polygon-service:1.0.0-SNAPSHOT
    container_name: polygon-service
    hostname: polygon-service
    environment:
      - PROFILE=staging
      - DOCUMENTDB_SERVER_HOST=documentdb-service
      - DOCUMENTDB_SERVER_PORT=27017
      - TRACING_SERVER_URL=http://tracing-service:9411
      - CONFIGURATION_SERVER_URL=http://configuration-service:8888
      - NAMING_SERVER_URL=http://naming-service:8761
    depends_on:
      - documentdb-service
      - configuration-service
      - naming-service
      - tracing-service