version: "3.9"

networks:
  sharenow:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/25
          gateway: 172.27.238.1

services:

  cache-service:
    image: redis:3.0.7-alpine
    container_name: cache-service
    hostname: cache-service
    ports:
      - "6379:6379"
    networks:
      sharenow:
        ipv4_address: 172.27.0.3

  documentdb-service:
    image: mongo:4.4-bionic
    container_name: documentdb-service
    hostname: documentdb-service
    volumes:
      - "/data/db:/opt/sharenow-coding-challenge-data/mongodb"
    ports:
      - "27017:27017"
    networks:
      sharenow:
        ipv4_address: 172.27.0.2

  tracing-service:
    image: openzipkin/zipkin
    container_name: tracing-service
    hostname: tracing-service
    ports:
      - "9411:9411"
    networks:
      sharenow:
        ipv4_address: 172.27.0.5

  car2godeveloper-service:
    image: car2godeveloper/api-for-coding-challenge
    container_name: car2godeveloper-service
    hostname: car2godeveloper-service
    ports:
      - "3000:3000"
    networks:
      sharenow:
        ipv4_address: 172.27.0.4

  naming-service:
    image: teenthofabud/sharenow-coding-challenge-naming-service:1.0.0-SNAPSHOT
    container_name: naming-service
    hostname: naming-service
    ports:
      - "8761:8761"
    networks:
      sharenow:
        ipv4_address: 172.27.0.6

  configuration-service:
    image: teenthofabud/sharenow-coding-challenge-configuration-service:1.0.0-SNAPSHOT
    container_name: configuration-service
    hostname: configuration-service
    ports:
      - "8888:8888"
    networks:
      sharenow:
        ipv4_address: 172.27.0.7
    environment:
      - NAMING_SERVER_URL=http://172.27.0.6:8761
    depends_on:
      - naming-service
    links:
      - naming-service
    restart: on-failure

  gateway-service:
    image: teenthofabud/sharenow-coding-challenge-gateway-service:1.0.0-SNAPSHOT
    container_name: gateway-service
    hostname: gateway-service
    networks:
      sharenow:
        ipv4_address: 172.27.0.8
    environment:
      - PROFILE=staging
      - NAMING_SERVER_URL=http://172.27.0.6:8761
      - CONFIGURATION_SERVER_URL=http://172.27.0.7:8888
    depends_on:
      - configuration-service
      - naming-service
    links:
      - configuration-service
      - naming-service
    ports:
      - "8081:8081"
    restart: on-failure

  polling-service:
    image: teenthofabud/sharenow-coding-challenge-polling-service:1.0.0-SNAPSHOT
    container_name: polling-service
    hostname: polling-service
    networks:
      sharenow:
        ipv4_address: 172.27.0.9
    environment:
      - PROFILE=staging
      - CACHE_SERVER_HOST=172.27.0.3
      - CACHE_SERVER_PORT=6379
      - CAR2GO_SERVER_URL=http://172.27.0.4:3000
      - NAMING_SERVER_URL=http://172.27.0.6:8761
      - CONFIGURATION_SERVER_URL=http://172.27.0.7:8888
    depends_on:
      - cache-service
      - configuration-service
      - naming-service
      - car2godeveloper-service
      - gateway-service
    links:
      - cache-service
      - configuration-service
      - naming-service
      - car2godeveloper-service
      - gateway-service
    ports:
      - "16080:16080"
    restart: on-failure

  car-service:
    image: teenthofabud/sharenow-coding-challenge-car-service:1.0.0-SNAPSHOT
    container_name: car-service
    hostname: car-service
    networks:
      sharenow:
        ipv4_address: 172.27.0.10
    environment:
      - PROFILE=staging
      - CACHE_SERVER_HOST=172.27.0.3
      - CACHE_SERVER_PORT=6379
      - TRACING_SERVER_URL=http://172.27.0.5:9411
      - NAMING_SERVER_URL=http://172.27.0.6:8761
      - CONFIGURATION_SERVER_URL=http://172.27.0.7:8888
    depends_on:
      - cache-service
      - tracing-service
      - configuration-service
      - polling-service
      - naming-service
      - gateway-service
    links:
      - cache-service
      - configuration-service
      - naming-service
      - car2godeveloper-service
      - gateway-service
    ports:
      - "17080:17080"
    restart: on-failure

  polygon-service:
    image: teenthofabud/sharenow-coding-challenge-polygon-service:1.0.0-SNAPSHOT
    container_name: polygon-service
    hostname: polygon-service
    networks:
      sharenow:
        ipv4_address: 172.27.0.11
    environment:
      - PROFILE=staging
      - DOCUMENTDB_SERVER_HOST=172.27.0.2
      - DOCUMENTDB_SERVER_PORT=27017
      - TRACING_SERVER_URL=http://172.27.0.5:9411
      - NAMING_SERVER_URL=http://172.27.0.6:8761
      - CONFIGURATION_SERVER_URL=http://172.27.0.7:8888
    depends_on:
      - documentdb-service
      - tracing-service
      - configuration-service
      - naming-service
      - gateway-service
    links:
      - documentdb-service
      - tracing-service
      - configuration-service
      - naming-service
      - gateway-service
    ports:
      - "18080:18080"
    restart: on-failure

  position-service:
    image: teenthofabud/sharenow-coding-challenge-position-service:1.0.0-SNAPSHOT
    container_name: position-service
    hostname: position-service
    networks:
      sharenow:
        ipv4_address: 172.27.0.12
    environment:
      - PROFILE=staging
      - TRACING_SERVER_URL=http://172.27.0.5:9411
      - NAMING_SERVER_URL=http://172.27.0.6:8761
      - CONFIGURATION_SERVER_URL=http://172.27.0.7:8888
      - CAR_SERVICE_URL=http://172.27.0.10:17080
      - POLYGON_SERVICE_URL=http://172.27.0.11:18080
    depends_on:
      - tracing-service
      - car-service
      - polygon-service
      - configuration-service
      - naming-service
      - gateway-service
    links:
      - tracing-service
      - car-service
      - polygon-service
      - configuration-service
      - naming-service
      - gateway-service
    ports:
      - "19080:19080"
    restart: on-failure