version: "3.9"

networks:
  sharenow:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/25
          gateway: 172.27.0.1

services:

  cache-service:
    image: redis:3.0.7-alpine
    container_name: cache-service
    hostname: cache-service
    ports:
    - "6379:6379"
    networks:
      sharenow:
        ipv4_address: 172.27.0.3

  documentdb-service:
    image: mongo:4.4-bionic
    container_name: documentdb-service
    hostname: documentdb-service
    volumes:
      - "/data/db:/opt/sharenow-coding-challenge-data/mongodb"
    ports:
      - "27017:27017"
    networks:
      sharenow:
        ipv4_address: 172.27.0.2

  tracing-service:
    image: openzipkin/zipkin
    container_name: tracing-service
    hostname: tracing-service
    ports:
      - "9411:9411"
    networks:
      sharenow:
        ipv4_address: 172.27.0.5

  car2godeveloper-service:
    image: car2godeveloper/api-for-coding-challenge
    container_name: car2godeveloper-service
    hostname: car2godeveloper-service
    ports:
      - "3000:3000"
    networks:
      sharenow:
        ipv4_address: 172.27.0.4

  naming-service:
    image: teenthofabud/sharenow-coding-challenge-naming-service:1.0.0-RELEASE
    container_name: naming-service
    hostname: naming-service
    ports:
      - "8761:8761"
    networks:
      sharenow:
        ipv4_address: 172.27.0.6

  configuration-service:
    image: teenthofabud/sharenow-coding-challenge-configuration-service:1.0.0-RELEASE
    container_name: configuration-service
    hostname: configuration-service
    ports:
      - "8888:8888"
    networks:
      sharenow:
        ipv4_address: 172.27.0.7
    environment:
      - PROJECT_BASE_DIR=./scripts/configuration-store
    restart: on-failure